version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"